package constants

// log_templates.go 集中定义结构化日志模板（≥25 条）。
// 业务字段变更时必须同步修改对应模板与调用处（屎山约束：日志模块全栈引用）。

const (
	LogServerStarted        = "server started, addr=%s, env=%s"
	LogServerShutdown       = "server shutdown, err=%v"
	LogConfigLoaded         = "config loaded, db_host=%s, db_port=%s, db_name=%s"
	LogDBConnected          = "database connected, host=%s, name=%s"
	LogDBMigrated           = "database migrated, models=%d"
	LogRedisConnected       = "redis connected, addr=%s"
	LogUserRegistered       = "user registered, user_id=%d, username=%s, role=%s"
	LogUserLogin            = "user login, user_id=%d, username=%s, role=%s"
	LogUserProfileUpdated   = "user profile updated, user_id=%d, nickname=%s"
	LogUserRoleUpdated      = "user role updated, operator=%d, target_user=%d, role=%s"
	LogProductCreated       = "product created, product_id=%d, seller_id=%d, category=%s, condition=%s"
	LogProductUpdated       = "product updated, product_id=%d, seller_id=%d, status=%s"
	LogProductOffShelf      = "product off shelf, product_id=%d, seller_id=%d, status=%s"
	LogProductViewed        = "product viewed, product_id=%d, view_count=%d"
	LogFavoriteAdded        = "favorite added, user_id=%d, product_id=%d"
	LogFavoriteRemoved      = "favorite removed, user_id=%d, product_id=%d"
	LogAddressCreated       = "address created, user_id=%d, address_id=%d, receiver=%s"
	LogAddressUpdated       = "address updated, user_id=%d, address_id=%d, receiver=%s"
	LogAddressDeleted       = "address deleted, user_id=%d, address_id=%d"
	LogCartAdded            = "cart item added, user_id=%d, product_id=%d, quantity=%d"
	LogCartUpdated          = "cart item updated, user_id=%d, cart_item_id=%d, quantity=%d"
	LogCartRemoved          = "cart item removed, user_id=%d, cart_item_id=%d"
	LogOrderCreated         = "order created, order_no=%s, buyer_id=%d, seller_id=%d, product_id=%d, status=%s"
	LogOrderPaid            = "order paid, order_no=%s, buyer_id=%d, status=%s"
	LogOrderShipped         = "order shipped, order_no=%s, seller_id=%d, status=%s"
	LogOrderReceived        = "order received, order_no=%s, buyer_id=%d, status=%s"
	LogOrderCompleted       = "order completed, order_no=%s, buyer_id=%d, status=%s"
	LogOrderCancelled       = "order cancelled, order_no=%s, operator=%d, status=%s"
	LogMessageSent          = "message sent, message_id=%d, sender_id=%d, receiver_id=%d, product_id=%d"
	LogMessageRead          = "message marked read, user_id=%d, count=%d"
	LogReviewCreated        = "review created, review_id=%d, order_id=%d, reviewer_id=%d, reviewee_id=%d, rating=%s"
	LogAuditCreated         = "audit log created, user_id=%d, module=%s, action=%s"
	LogAuditListed          = "audit logs listed, operator=%d, page=%d, page_size=%d"
	LogWSConnected          = "websocket connected, user_id=%d"
	LogWSDisconnected       = "websocket disconnected, user_id=%d"
	LogWSPublishFailed      = "websocket publish failed, receiver_id=%d, err=%v"
	LogRateLimited          = "request rate limited, user_id=%d, path=%s"
	LogRequestPanic         = "request panic recovered, path=%s, err=%v"
	LogRequestHandled       = "request handled, request_id=%s, method=%s, path=%s, status=%d, latency_ms=%d"
	LogInvalidState         = "invalid state transition, entity=%s, id=%d, from=%s, to=%s, operator=%d"
	LogInvalidEnumValue     = "invalid enum value, entity=%s, field=%s, value=%s"
	LogRepoQueryFailed      = "repository query failed, entity=%s, op=%s, err=%v"
)
